version: '3.8'

services:
# ================= DATA BASES ===================
  postgres-db:
    container_name: postgres-db
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: manutencao_equipamentos
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      TZ: America/Sao_Paulo
      PGTZ: America/Sao_Paulo 
    networks:
      - manutencao-equipamentos-net
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "admin"]
      interval: 5s
      timeout: 5s
      retries: 5

# =============== MICROSERVIÃ‡OS ==================
# =============== BACKEND ========================
  backend:
    container_name: backend
    build:
      context: ./back-end
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - TZ=America/Sao_Paulo
      - JAVA_TOOL_OPTIONS=-Duser.timezone=America/Sao_Paulo
    depends_on:
      postgres-db:
        condition: service_healthy
    networks:
      - manutencao-equipamentos-net

# =============== NETWORK ========================
networks:
  manutencao-equipamentos-net:
    driver: bridge